# Generated by Django 3.2.7 on 2021-09-22 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nannews', '0003_auto_20210922_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='image',
            field=models.FileField(default=1, upload_to='image_site'),
            preserve_default=False,
        ),
    ]
