# Generated by Django 3.2.7 on 2021-09-22 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nannews', '0004_site_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='image',
            field=models.FileField(default=1, upload_to='image_team'),
            preserve_default=False,
        ),
    ]
