# Generated by Django 3.2.7 on 2021-10-01 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nannews', '0007_alter_config_history'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='social',
            name='link',
        ),
        migrations.RemoveField(
            model_name='team',
            name='social',
        ),
        migrations.AddField(
            model_name='phone',
            name='site',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='site_phone', to='nannews.site'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='SocialUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('link', models.URLField()),
                ('social', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_social', to='nannews.social')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_social', to='nannews.team')),
            ],
            options={
                'verbose_name': 'Social_User',
                'verbose_name_plural': 'Social_Users',
            },
        ),
    ]
