# Generated by Django 3.2.7 on 2021-11-25 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nannews', '0010_alter_config_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialuser',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_social_user', to='nannews.team'),
        ),
    ]
